language: go

go:
  - "1.11"
  - "stable"

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - go test ./... -v -race

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: build
      script: make build

    - stage: test
      script: make test
